### PR TITLE
Social media website - Milestone: friendships v1

### PR DESCRIPTION
**Pull request by gango-anan**
# Milestone5: friendships.
## In this milestone, I:
- Created a Bond model which represents the friendship among users.
- Added the feature features that facilitate friendship among users.
- Added associations that enable users to follow each other.
- Added the model specs for User and Bond models to test whether the associations are behaving as expected.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
#Status: Changes Required :recycle: 

### Hello @gango-anan, good job with your project :+1: however there are some changes to be made:

- [ ] User can invite friends, currently I do not see the option to add friends in the app display ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright]
- [ ] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Please add more tests
- [ ] Please remove the logic from the view folder, there should not be any logic 

### Please implement these changes and ask for another code review whenever you are ready

_**If you have any question related to the required changes feel free to text me on chat @GzimAsani**_

HAPPY CODING :computer: :desktop_computer:

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work. 💻 👀 ✨ 
- Great job implementing most of the changes required by the previous TSE.

## However, there are some changes required 👀 🧰 🔨 🔧 
- Your code seems to be mostly in order but when trying to run your project in a fresh installation I get the following error on my browser screen:
image

Please make sure that your project can run on a new installation by cloning it and setting it up on your own computer from scratch before submitting for another code review.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello there :)
Great job working on this milestone and mostly meeting its requirements. However, there are some missed changes you need to do before moving on to the next one :)
Please keep up the great work :D

<hr>

- [ ] A user should only see the posts that belong to them or their friends. Currently, this logic doesn't apply. Please do so!
friends_timeline

- [ ] The "Invite to friendship" button that shows up in the All Users' page doesn't work, it only works inside the user's profile page. Kindly fix that issue.
- [ ] Currently, when I send a friendship invitation, it counts as a friend without the need of accepting the request. Please fix this issue.
- [ ] As requested earlier, please add more tests for your app's features.

<hr>

Kindly do the above changes, then ask for another CRR :)
Good luck and happy coding 👨‍💻💻

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi Galiwango!
Great job on this milestone:clap::clap:. We are almost there. Thank you for implementing almost all the changes requested by the last reviewer:thumbsup:.**

**Major highlights**

- User can invite friends and can see friendship request
- Users can accept friendship requests to start friendships. Users can reject friendship.
- The codebase is neat and clearly written.
- There are no logic in view.

**To improve**

- [ ] Currently, the tests only cover the Model. We also need to write the same for the controller.

Make the above-required change and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy coding:blush:
Eric Enaburekhan

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Congratulations on completing this milestone and well done on the implementing the specs for controller.

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next milestone.

### Fix this changes before you proceed.

- [ ] Your commit messages should be capitalized, and written in the imperative tense. You can watch this [video](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6) on how to edit your commit messages using git rebase
 See [Git Commit Best Practices](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) for more insights

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
